# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0003_topic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
