# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0005_topic_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='crated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
