# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0007_auto_20170402_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
