# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0008_auto_20170402_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='crated',
            new_name='created',
        ),
    ]
